---

- name: Gather package facts
  package_facts:
    manager: apt

- debug:
    msg: "ansible_local.aptarch.dpkg_architecture: {{ ansible_local.aptarch.dpkg_architecture }}"
- debug:
    var: ansible_lsb
#- debug:
#    var: ansible_facts.packages
- debug:
    msg: "ansible_distribution_release: {{ ansible_distribution_release }}"

- name: install check_mk from repo
  apt:
    name: "{{ item.key }}"
    state: latest
  with_dict: "{{ checkmk_packages }}"
  when:
    - checkmk_packages_install
    - item.key not in ansible_facts.packages
    - ansible_distribution in ['Debian', 'Raspbian'] and ansible_lsb.id == ansible_distribution and not ansible_distribution_release in ['jessie', 'stretch', 'buster',]


- name: install check_mk from sid
  apt:
    deb: "{{ checkmk_baseurl }}/{{ item.key }}_{{ item.value.version }}_{{ item.value.arch|default(ansible_local.aptarch.dpkg_architecture) }}.deb"
  with_dict: "{{ checkmk_packages }}"
  when:
    - checkmk_packages_install
    - item.key not in ansible_facts.packages
    - ansible_lsb.id in ['Debian', 'Raspbian'] and ansible_distribution_release in ['jessie', 'stretch', 'buster',]

- name: xinetd package
  apt:
    name: xinetd
    state: present
  when: checkmk_agent.use_xinetd

- name: configure /etc/xinetd.d/check_mk
  template:
    dest: /etc/xinetd.d/check_mk
    src: xinet.d-check_mk.j2
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 
    - restart xinetd
  when: checkmk_agent.use_xinetd

- name: install nagios-plugins
  apt:
    name: monitoring-plugins
    state: present

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu
